theme = "gruvbox"

[editor]
line-number = "relative"
rulers = [80, 100, 120]
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "diagnostics",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
right = [
  "file-type",
  "selections",
  "register",
  "position-percentage",
  "position",
]

[keys.normal]
"^" = "goto_line_start"
"$" = "goto_line_end"
"g" = { "d" = ["hsplit", "jump_view_down", "goto_definition"] }

[keys.normal.","]
"r" = ":reflow"
