theme = "gruvbox-material"

[editor]
line-number = "relative"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[keys.normal]
"^" = "goto_line_start"
"$" = "goto_line_end"
"g" = { "d" = ["hsplit", "jump_view_down", "goto_definition"] }
